sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
env:
  matrix:
    - DB=postgres TEST=pulp
    - DB=mariadb TEST=pulp
matrix:
  exclude:
    - python: '3.6'
      env: DB=mariadb TEST=pulp
  fast_finish: true
services:
  - postgresql
  - mariadb
addons:
  apt:
    packages:
      - httpie
      - jq
  # postgres versions provided by el7 RHSCL (lowest supportable version)
  postgresql: '9.6'
  mariadb: '10.3'
before_install: .travis/before_install.sh
install: .travis/install.sh
before_script: .travis/before_script.sh
script:
  - .travis/script.sh
#jobs:
#  include:
#  - stage: deploy
#    script: skip
#    deploy:
#      provider: pypi
#      distributions: sdist bdist_wheel
#      user: <pypi username>
#      password:
#        secure: <encrypted pypi password>
#      on:
#        tags: true
#    if: tag IS present
