sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
    # python versions used in el7 SCL & supported fedora
    - "3.6"
    - "3.7"
env:
  matrix:
    - DB=postgres TEST=pulp
    - DB=postgres TEST=docs
    - DB=mariadb TEST=pulp
    

matrix:
  exclude:
    - python: '3.6'
      env: DB=mariadb TEST=pulp

  fast_finish: true
services:
    - postgresql
    - redis-server
    - mariadb
addons:
  apt:
    packages:
      - httpie
      - jq
  # postgres versions provided by el7 RHSCL (lowest supportable version)
  postgresql: '9.6'
  mariadb: '10.3'
before_install: .travis/before_install.sh
install: .travis/install.sh
before_script: .travis/before_script.sh
script: .travis/script.sh
after_failure:
  - sh -c "cat ~/django_runserver.log"
  - sh -c "cat ~/resource_manager.log"
  - sh -c "cat ~/reserved_workers-1.log"
jobs:
  include:
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: pulp
      password:
        secure: $PYPI_PASSWORD
      on:
        tags: true
    if: tag IS present
  - stage: publish-client-gem
    script: bash .travis/publish_client_gem.sh
    env:
      - DB=postgres
      - TEST=bindings
    if: type = cron

